import './globals.css'
import { Inter } from 'next/font/google'
import {Providers} from "./contextscontexts/providers";
import Nav from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light">
        <body className={inter.className}>
          <providers> 
            <Nav />
            {children}
          </providers>  
        </body>
    </html>
  )
}
