import './globals.css'
import { Kumbh_Sans } from 'next/font/google'
import {Providers} from "./contexts/providers";
import {CartProvider} from './contexts/CartProvider'
import Nav from './components/Navbar'

const kumbh = Kumbh_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="light" >
        <body className={kumbh.className}>
          <Providers>
            <CartProvider>
              <Nav />
              <main className="max-w-5xl w-full sm:px-6">
                {children}
              </main>
            </CartProvider>
          </Providers>        
        </body>
    </html>
  )
}
